### ISSUE TITLE
TASK - Post org migration tasks (lab-extension)

### ISSUE THREAD

**Issue by trallard** [conda-incubator/jupyterlab-conda-store#13]
Now that we have migrated the repository to the conda-incubator organisation there are several follow-up tasks to complete:

```[tasklist]
### Tasks
- [x] Ensure documentation can be built and is accessible (through and URL)
- [x] Update `.github/workflows` as needed
- [x] Update issue and PR templates in the repository - https://github.com/conda-incubator/jupyterlab-conda-store/pull/16
- [x] Ensure the repo points to the conda CoC - https://github.com/conda-incubator/jupyterlab-conda-store/pull/15
- [x] Align labels with those of the other conda-store repos
- [x] Fix broken links in README - https://github.com/conda-incubator/jupyterlab-conda-store/pull/15
- [ ] Revisit and document release process
```
